# Generated by Django 2.0.6 on 2018-06-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180625_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualification',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
