# Generated by Django 2.0.6 on 2018-06-25 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20180625_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
