# Generated by Django 2.0.6 on 2018-06-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_remove_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_num',
            field=models.IntegerField(null=True),
        ),
    ]
